interface Props {
  closeModal?: () => void;
}

export default function Sample1({ closeModal }: Props) {
  return (
    <div className="absolute left-[50%] top-[50%] h-[300px] w-[300px] translate-x-[-50%] translate-y-[-50%] overflow-y-auto bg-white">
      <button type="button" onClick={closeModal}>
        close!
      </button>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1</p>
      <p>Hello I&apos;m Sample1 끝!</p>
    </div>
  );
}
